param_grid: 
    max_depth: [3, 4, 5]
    min_child_weight: [7, 8, 9, 10] 
    n_estimators: [25, 50, 100] 
    colsample_bytree: [0.6, 0.8, 1.0]
    subsample: [0.6, 0.8, 1.0]
    enable_categorical: [False]
    random_state: [1]
cv: 10
n_jobs: -1
verbose: True                                                                