param_grid: 
    max_depth: [3, 4, 5,]
    n_estimators: [25, 50, 100, 200, 400]
    min_samples_split: [6, 8, 10]
    random_state: [1]
cv: 10
n_jobs: -1
verbose: True

                                                                               